import { Formation } from './types';

export const FORMATIONS: Formation[] = [
  {
    id: '4-3-3',
    name: '4-3-3 (Attack)',
    category: 'Attacking',
    description: 'Classic high-tempo system with wide wingers and a balanced midfield trio.',
    slots: [
      { positionId: 'slot-0', label: 'GK', role: 'Goalkeeper', x: 50, y: 88 },
      { positionId: 'slot-1', label: 'LB', role: 'Defender', x: 15, y: 72 },
      { positionId: 'slot-2', label: 'LCB', role: 'Defender', x: 38, y: 75 },
      { positionId: 'slot-3', label: 'RCB', role: 'Defender', x: 62, y: 75 },
      { positionId: 'slot-4', label: 'RB', role: 'Defender', x: 85, y: 72 },
      { positionId: 'slot-5', label: 'LCM', role: 'Midfielder', x: 26, y: 47 },
      { positionId: 'slot-6', label: 'CDM', role: 'Midfielder', x: 50, y: 53 },
      { positionId: 'slot-7', label: 'RCM', role: 'Midfielder', x: 74, y: 47 },
      { positionId: 'slot-8', label: 'LW', role: 'Forward', x: 18, y: 22 },
      { positionId: 'slot-9', label: 'ST', role: 'Forward', x: 50, y: 15 },
      { positionId: 'slot-10', label: 'RW', role: 'Forward', x: 82, y: 22 },
    ],
  },
  {
    id: '4-2-3-1',
    name: '4-2-3-1 (Wide)',
    category: 'Balanced',
    description: 'Modern double-pivot tactical standard with an attacking playmaker and wingers.',
    slots: [
      { positionId: 'slot-0', label: 'GK', role: 'Goalkeeper', x: 50, y: 88 },
      { positionId: 'slot-1', label: 'LB', role: 'Defender', x: 15, y: 74 },
      { positionId: 'slot-2', label: 'LCB', role: 'Defender', x: 38, y: 76 },
      { positionId: 'slot-3', label: 'RCB', role: 'Defender', x: 62, y: 76 },
      { positionId: 'slot-4', label: 'RB', role: 'Defender', x: 85, y: 74 },
      { positionId: 'slot-5', label: 'LDM', role: 'Midfielder', x: 35, y: 56 },
      { positionId: 'slot-6', label: 'RDM', role: 'Midfielder', x: 65, y: 56 },
      { positionId: 'slot-7', label: 'LAM', role: 'Midfielder', x: 18, y: 35 },
      { positionId: 'slot-8', label: 'CAM', role: 'Midfielder', x: 50, y: 33 },
      { positionId: 'slot-9', label: 'RAM', role: 'Midfielder', x: 82, y: 35 },
      { positionId: 'slot-10', label: 'ST', role: 'Forward', x: 50, y: 15 },
    ],
  },
  {
    id: '4-4-2',
    name: '4-4-2 (Classic)',
    category: 'Balanced',
    description: 'Traditional solid two banks of four with dual striking partnership.',
    slots: [
      { positionId: 'slot-0', label: 'GK', role: 'Goalkeeper', x: 50, y: 88 },
      { positionId: 'slot-1', label: 'LB', role: 'Defender', x: 15, y: 73 },
      { positionId: 'slot-2', label: 'LCB', role: 'Defender', x: 38, y: 75 },
      { positionId: 'slot-3', label: 'RCB', role: 'Defender', x: 62, y: 75 },
      { positionId: 'slot-4', label: 'RB', role: 'Defender', x: 85, y: 73 },
      { positionId: 'slot-5', label: 'LM', role: 'Midfielder', x: 15, y: 46 },
      { positionId: 'slot-6', label: 'LCM', role: 'Midfielder', x: 38, y: 48 },
      { positionId: 'slot-7', label: 'RCM', role: 'Midfielder', x: 62, y: 48 },
      { positionId: 'slot-8', label: 'RM', role: 'Midfielder', x: 85, y: 46 },
      { positionId: 'slot-9', label: 'LST', role: 'Forward', x: 35, y: 18 },
      { positionId: 'slot-10', label: 'RST', role: 'Forward', x: 65, y: 18 },
    ],
  },
  {
    id: '3-5-2',
    name: '3-5-2 (Wing-Backs)',
    category: 'Balanced',
    description: 'Three central defenders supported by dynamic wing-backs across the flanks.',
    slots: [
      { positionId: 'slot-0', label: 'GK', role: 'Goalkeeper', x: 50, y: 88 },
      { positionId: 'slot-1', label: 'LCB', role: 'Defender', x: 26, y: 74 },
      { positionId: 'slot-2', label: 'CB', role: 'Defender', x: 50, y: 76 },
      { positionId: 'slot-3', label: 'RCB', role: 'Defender', x: 74, y: 74 },
      { positionId: 'slot-4', label: 'LWB', role: 'Midfielder', x: 14, y: 47 },
      { positionId: 'slot-5', label: 'LDM', role: 'Midfielder', x: 35, y: 55 },
      { positionId: 'slot-6', label: 'CAM', role: 'Midfielder', x: 50, y: 35 },
      { positionId: 'slot-7', label: 'RDM', role: 'Midfielder', x: 65, y: 55 },
      { positionId: 'slot-8', label: 'RWB', role: 'Midfielder', x: 86, y: 47 },
      { positionId: 'slot-9', label: 'LST', role: 'Forward', x: 35, y: 17 },
      { positionId: 'slot-10', label: 'RST', role: 'Forward', x: 65, y: 17 },
    ],
  },
  {
    id: '3-4-3',
    name: '3-4-3 (Front Press)',
    category: 'Attacking',
    description: 'Aggressive wide pressing structure with a formidable front 3.',
    slots: [
      { positionId: 'slot-0', label: 'GK', role: 'Goalkeeper', x: 50, y: 88 },
      { positionId: 'slot-1', label: 'LCB', role: 'Defender', x: 25, y: 74 },
      { positionId: 'slot-2', label: 'CB', role: 'Defender', x: 50, y: 76 },
      { positionId: 'slot-3', label: 'RCB', role: 'Defender', x: 75, y: 74 },
      { positionId: 'slot-4', label: 'LM', role: 'Midfielder', x: 15, y: 48 },
      { positionId: 'slot-5', label: 'LCM', role: 'Midfielder', x: 38, y: 50 },
      { positionId: 'slot-6', label: 'RCM', role: 'Midfielder', x: 62, y: 50 },
      { positionId: 'slot-7', label: 'RM', role: 'Midfielder', x: 85, y: 48 },
      { positionId: 'slot-8', label: 'LW', role: 'Forward', x: 20, y: 20 },
      { positionId: 'slot-9', label: 'ST', role: 'Forward', x: 50, y: 15 },
      { positionId: 'slot-10', label: 'RW', role: 'Forward', x: 80, y: 20 },
    ],
  },
  {
    id: '5-3-2',
    name: '5-3-2 (Fortress)',
    category: 'Defensive',
    description: 'Resilient 5-man defensive chain suited for quick counter-attacks.',
    slots: [
      { positionId: 'slot-0', label: 'GK', role: 'Goalkeeper', x: 50, y: 88 },
      { positionId: 'slot-1', label: 'LWB', role: 'Defender', x: 12, y: 68 },
      { positionId: 'slot-2', label: 'LCB', role: 'Defender', x: 30, y: 75 },
      { positionId: 'slot-3', label: 'CB', role: 'Defender', x: 50, y: 77 },
      { positionId: 'slot-4', label: 'RCB', role: 'Defender', x: 70, y: 75 },
      { positionId: 'slot-5', label: 'RWB', role: 'Defender', x: 88, y: 68 },
      { positionId: 'slot-6', label: 'LCM', role: 'Midfielder', x: 28, y: 46 },
      { positionId: 'slot-7', label: 'CM', role: 'Midfielder', x: 50, y: 49 },
      { positionId: 'slot-8', label: 'RCM', role: 'Midfielder', x: 72, y: 46 },
      { positionId: 'slot-9', label: 'LST', role: 'Forward', x: 35, y: 18 },
      { positionId: 'slot-10', label: 'RST', role: 'Forward', x: 65, y: 18 },
    ],
  },
  {
    id: '4-1-2-1-2',
    name: '4-1-2-1-2 (Diamond)',
    category: 'Balanced',
    description: 'Central midfield dominance with a dedicated CDM, CAM, and two strikers.',
    slots: [
      { positionId: 'slot-0', label: 'GK', role: 'Goalkeeper', x: 50, y: 88 },
      { positionId: 'slot-1', label: 'LB', role: 'Defender', x: 15, y: 73 },
      { positionId: 'slot-2', label: 'LCB', role: 'Defender', x: 38, y: 75 },
      { positionId: 'slot-3', label: 'RCB', role: 'Defender', x: 62, y: 75 },
      { positionId: 'slot-4', label: 'RB', role: 'Defender', x: 85, y: 73 },
      { positionId: 'slot-5', label: 'CDM', role: 'Midfielder', x: 50, y: 58 },
      { positionId: 'slot-6', label: 'LM', role: 'Midfielder', x: 22, y: 45 },
      { positionId: 'slot-7', label: 'RM', role: 'Midfielder', x: 78, y: 45 },
      { positionId: 'slot-8', label: 'CAM', role: 'Midfielder', x: 50, y: 32 },
      { positionId: 'slot-9', label: 'LST', role: 'Forward', x: 35, y: 16 },
      { positionId: 'slot-10', label: 'RST', role: 'Forward', x: 65, y: 16 },
    ],
  },
];

export const DEFAULT_FORMATION_ID = '4-3-3';

export function getFormation(id: string): Formation {
  return FORMATIONS.find((f) => f.id === id) || FORMATIONS[0];
}
