import { Player, PlayerCategory, PlayerPosition, getRoleFromPosition } from './types';
import { generatePlayerPhoto } from './player-photo';

interface RawPlayer {
  name: string;
  firstName: string;
  lastName: string;
  nationality: string;
  nationalityCode: string;
  position: PlayerPosition;
  dateOfBirth: string;
  team: string;
  league: string;
  category: PlayerCategory;
}

const RAW_PLAYERS: RawPlayer[] = [
  // ===== LEGENDS =====
  { name: 'Pelé', firstName: 'Edson', lastName: 'Arantes do Nascimento', nationality: 'Brazil', nationalityCode: 'BR', position: 'ST', dateOfBirth: '1940-10-23', team: 'Santos', league: 'Campeonato Brasileiro', category: 'LEGEND' },
  { name: 'Diego Maradona', firstName: 'Diego', lastName: 'Maradona', nationality: 'Argentina', nationalityCode: 'AR', position: 'CAM', dateOfBirth: '1960-10-30', team: 'Napoli', league: 'Serie A', category: 'LEGEND' },
  { name: 'Johan Cruyff', firstName: 'Johan', lastName: 'Cruyff', nationality: 'Netherlands', nationalityCode: 'NL', position: 'CAM', dateOfBirth: '1947-04-25', team: 'Ajax', league: 'Eredivisie', category: 'LEGEND' },
  { name: 'Franz Beckenbauer', firstName: 'Franz', lastName: 'Beckenbauer', nationality: 'Germany', nationalityCode: 'DE', position: 'CB', dateOfBirth: '1945-09-11', team: 'Bayern Munich', league: 'Bundesliga', category: 'LEGEND' },
  { name: 'Zinedine Zidane', firstName: 'Zinedine', lastName: 'Zidane', nationality: 'France', nationalityCode: 'FR', position: 'CAM', dateOfBirth: '1972-06-23', team: 'Real Madrid', league: 'La Liga', category: 'LEGEND' },
  { name: 'Ronaldo Nazário', firstName: 'Ronaldo', lastName: 'Nazário', nationality: 'Brazil', nationalityCode: 'BR', position: 'ST', dateOfBirth: '1976-09-22', team: 'Inter Milan', league: 'Serie A', category: 'LEGEND' },
  { name: 'Pelé', firstName: 'Edson', lastName: 'Arantes do Nascimento', nationality: 'Brazil', nationalityCode: 'BR', position: 'ST', dateOfBirth: '1940-10-23', team: 'Santos', league: 'Campeonato Brasileiro', category: 'LEGEND' },
  { name: 'Alfredo Di Stéfano', firstName: 'Alfredo', lastName: 'Di Stéfano', nationality: 'Argentina', nationalityCode: 'AR', position: 'ST', dateOfBirth: '1926-07-04', team: 'Real Madrid', league: 'La Liga', category: 'LEGEND' },
  { name: 'George Best', firstName: 'George', lastName: 'Best', nationality: 'Northern Ireland', nationalityCode: 'GB', position: 'RW', dateOfBirth: '1946-05-22', team: 'Manchester United', league: 'Premier League', category: 'LEGEND' },
  { name: 'Ferenc Puskás', firstName: 'Ferenc', lastName: 'Puskás', nationality: 'Hungary', nationalityCode: 'HU', position: 'ST', dateOfBirth: '1927-04-02', team: 'Real Madrid', league: 'La Liga', category: 'LEGEND' },
  { name: 'Garrincha', firstName: 'Manoel', lastName: 'dos Santos', nationality: 'Brazil', nationalityCode: 'BR', position: 'RW', dateOfBirth: '1933-10-28', team: 'Botafogo', league: 'Campeonato Brasileiro', category: 'LEGEND' },
  { name: 'Paolo Maldini', firstName: 'Paolo', lastName: 'Maldini', nationality: 'Italy', nationalityCode: 'IT', position: 'CB', dateOfBirth: '1968-06-26', team: 'AC Milan', league: 'Serie A', category: 'LEGEND' },
  { name: 'Bobby Charlton', firstName: 'Bobby', lastName: 'Charlton', nationality: 'England', nationalityCode: 'GB', position: 'CAM', dateOfBirth: '1937-10-11', team: 'Manchester United', league: 'Premier League', category: 'LEGEND' },
  { name: 'Eusébio', firstName: 'Eusébio', lastName: 'da Silva Ferreira', nationality: 'Portugal', nationalityCode: 'PT', position: 'ST', dateOfBirth: '1942-01-25', team: 'Benfica', league: 'Primeira Liga', category: 'LEGEND' },

  // ===== ICONS =====
  { name: 'Cristiano Ronaldo', firstName: 'Cristiano', lastName: 'Ronaldo', nationality: 'Portugal', nationalityCode: 'PT', position: 'ST', dateOfBirth: '1985-02-05', team: 'Al Nassr', league: 'Saudi Pro League', category: 'ICON' },
  { name: 'Lionel Messi', firstName: 'Lionel', lastName: 'Messi', nationality: 'Argentina', nationalityCode: 'AR', position: 'RW', dateOfBirth: '1987-06-24', team: 'Inter Miami', league: 'MLS', category: 'ICON' },
  { name: 'Ronaldinho', firstName: 'Ronaldo', lastName: 'de Assis Moreira', nationality: 'Brazil', nationalityCode: 'BR', position: 'CAM', dateOfBirth: '1980-03-21', team: 'Barcelona', league: 'La Liga', category: 'ICON' },
  { name: 'Thierry Henry', firstName: 'Thierry', lastName: 'Henry', nationality: 'France', nationalityCode: 'FR', position: 'ST', dateOfBirth: '1977-08-17', team: 'Arsenal', league: 'Premier League', category: 'ICON' },
  { name: 'Andrés Iniesta', firstName: 'Andrés', lastName: 'Iniesta', nationality: 'Spain', nationalityCode: 'ES', position: 'CM', dateOfBirth: '1984-05-11', team: 'Barcelona', league: 'La Liga', category: 'ICON' },
  { name: 'Xavi', firstName: 'Xavier', lastName: 'Hernández', nationality: 'Spain', nationalityCode: 'ES', position: 'CM', dateOfBirth: '1980-01-25', team: 'Barcelona', league: 'La Liga', category: 'ICON' },
  { name: 'Steven Gerrard', firstName: 'Steven', lastName: 'Gerrard', nationality: 'England', nationalityCode: 'GB', position: 'CM', dateOfBirth: '1980-05-30', team: 'Liverpool', league: 'Premier League', category: 'ICON' },
  { name: 'Kaka', firstName: 'Ricardo', lastName: 'Izecson', nationality: 'Brazil', nationalityCode: 'BR', position: 'CAM', dateOfBirth: '1982-04-22', team: 'AC Milan', league: 'Serie A', category: 'ICON' },
  { name: 'Frank Lampard', firstName: 'Frank', lastName: 'Lampard', nationality: 'England', nationalityCode: 'GB', position: 'CM', dateOfBirth: '1978-06-20', team: 'Chelsea', league: 'Premier League', category: 'ICON' },
  { name: 'Didier Drogba', firstName: 'Didier', lastName: 'Drogba', nationality: 'Ivory Coast', nationalityCode: 'CI', position: 'ST', dateOfBirth: '1978-03-11', team: 'Chelsea', league: 'Premier League', category: 'ICON' },
  { name: 'Roberto Carlos', firstName: 'Roberto', lastName: 'Carlos', nationality: 'Brazil', nationalityCode: 'BR', position: 'LB', dateOfBirth: '1973-04-10', team: 'Real Madrid', league: 'La Liga', category: 'ICON' },
  { name: 'Carlos Puyol', firstName: 'Carlos', lastName: 'Puyol', nationality: 'Spain', nationalityCode: 'ES', position: 'CB', dateOfBirth: '1978-04-13', team: 'Barcelona', league: 'La Liga', category: 'ICON' },
  { name: 'Iker Casillas', firstName: 'Iker', lastName: 'Casillas', nationality: 'Spain', nationalityCode: 'ES', position: 'GK', dateOfBirth: '1981-05-20', team: 'Real Madrid', league: 'La Liga', category: 'ICON' },
  { name: 'Gianluigi Buffon', firstName: 'Gianluigi', lastName: 'Buffon', nationality: 'Italy', nationalityCode: 'IT', position: 'GK', dateOfBirth: '1978-01-28', team: 'Juventus', league: 'Serie A', category: 'ICON' },
  { name: 'Andrea Pirlo', firstName: 'Andrea', lastName: 'Pirlo', nationality: 'Italy', nationalityCode: 'IT', position: 'CDM', dateOfBirth: '1979-05-19', team: 'Juventus', league: 'Serie A', category: 'ICON' },
  { name: 'Luís Figo', firstName: 'Luís', lastName: 'Figo', nationality: 'Portugal', nationalityCode: 'PT', position: 'RW', dateOfBirth: '1972-11-04', team: 'Real Madrid', league: 'La Liga', category: 'ICON' },
  { name: 'Samuel Eto\'o', firstName: 'Samuel', lastName: 'Eto\'o', nationality: 'Cameroon', nationalityCode: 'CM', position: 'ST', dateOfBirth: '1981-03-10', team: 'Barcelona', league: 'La Liga', category: 'ICON' },
  { name: 'Michael Ballack', firstName: 'Michael', lastName: 'Ballack', nationality: 'Germany', nationalityCode: 'DE', position: 'CM', dateOfBirth: '1976-09-26', team: 'Chelsea', league: 'Premier League', category: 'ICON' },

  // ===== HEROES =====
  { name: 'Neymar Jr', firstName: 'Neymar', lastName: 'da Silva', nationality: 'Brazil', nationalityCode: 'BR', position: 'LW', dateOfBirth: '1992-02-05', team: 'Santos', league: 'Campeonato Brasileiro', category: 'HERO' },
  { name: 'Robert Lewandowski', firstName: 'Robert', lastName: 'Lewandowski', nationality: 'Poland', nationalityCode: 'PL', position: 'ST', dateOfBirth: '1988-08-21', team: 'Barcelona', league: 'La Liga', category: 'HERO' },
  { name: 'Sergio Ramos', firstName: 'Sergio', lastName: 'Ramos', nationality: 'Spain', nationalityCode: 'ES', position: 'CB', dateOfBirth: '1986-03-30', team: 'Paris Saint-Germain', league: 'Ligue 1', category: 'HERO' },
  { name: 'Luka Modrić', firstName: 'Luka', lastName: 'Modrić', nationality: 'Croatia', nationalityCode: 'HR', position: 'CM', dateOfBirth: '1985-09-09', team: 'Real Madrid', league: 'La Liga', category: 'HERO' },
  { name: 'Gareth Bale', firstName: 'Gareth', lastName: 'Bale', nationality: 'Wales', nationalityCode: 'GB', position: 'LW', dateOfBirth: '1989-07-16', team: 'Real Madrid', league: 'La Liga', category: 'HERO' },
  { name: 'Mohamed Salah', firstName: 'Mohamed', lastName: 'Salah', nationality: 'Egypt', nationalityCode: 'EG', position: 'RW', dateOfBirth: '1992-06-15', team: 'Liverpool', league: 'Premier League', category: 'HERO' },
  { name: 'Kevin De Bruyne', firstName: 'Kevin', lastName: 'De Bruyne', nationality: 'Belgium', nationalityCode: 'BE', position: 'CM', dateOfBirth: '1991-06-28', team: 'Manchester City', league: 'Premier League', category: 'HERO' },
  { name: 'Virgil van Dijk', firstName: 'Virgil', lastName: 'van Dijk', nationality: 'Netherlands', nationalityCode: 'NL', position: 'CB', dateOfBirth: '1991-07-08', team: 'Liverpool', league: 'Premier League', category: 'HERO' },
  { name: 'Sergio Agüero', firstName: 'Sergio', lastName: 'Agüero', nationality: 'Argentina', nationalityCode: 'AR', position: 'ST', dateOfBirth: '1988-06-02', team: 'Manchester City', league: 'Premier League', category: 'HERO' },
  { name: 'David Beckham', firstName: 'David', lastName: 'Beckham', nationality: 'England', nationalityCode: 'GB', position: 'RM', dateOfBirth: '1975-05-02', team: 'LA Galaxy', league: 'MLS', category: 'HERO' },
  { name: 'Zlatan Ibrahimović', firstName: 'Zlatan', lastName: 'Ibrahimović', nationality: 'Sweden', nationalityCode: 'SE', position: 'ST', dateOfBirth: '1981-10-03', team: 'AC Milan', league: 'Serie A', category: 'HERO' },
  { name: 'Antoine Griezmann', firstName: 'Antoine', lastName: 'Griezmann', nationality: 'France', nationalityCode: 'FR', position: 'CAM', dateOfBirth: '1991-03-21', team: 'Atlético Madrid', league: 'La Liga', category: 'HERO' },
  { name: 'Toni Kroos', firstName: 'Toni', lastName: 'Kroos', nationality: 'Germany', nationalityCode: 'DE', position: 'CM', dateOfBirth: '1990-01-04', team: 'Real Madrid', league: 'La Liga', category: 'HERO' },
  { name: 'N\'Golo Kanté', firstName: 'N\'Golo', lastName: 'Kanté', nationality: 'France', nationalityCode: 'FR', position: 'CDM', dateOfBirth: '1991-03-29', team: 'Al-Ittihad', league: 'Saudi Pro League', category: 'HERO' },
  { name: 'Harry Kane', firstName: 'Harry', lastName: 'Kane', nationality: 'England', nationalityCode: 'GB', position: 'ST', dateOfBirth: '1993-07-28', team: 'Bayern Munich', league: 'Bundesliga', category: 'HERO' },
  { name: 'Kylian Mbappé', firstName: 'Kylian', lastName: 'Mbappé', nationality: 'France', nationalityCode: 'FR', position: 'ST', dateOfBirth: '1998-12-20', team: 'Real Madrid', league: 'La Liga', category: 'HERO' },
  { name: 'Erling Haaland', firstName: 'Erling', lastName: 'Haaland', nationality: 'Norway', nationalityCode: 'NO', position: 'ST', dateOfBirth: '2000-07-21', team: 'Manchester City', league: 'Premier League', category: 'HERO' },
  { name: 'Son Heung-min', firstName: 'Heung-min', lastName: 'Son', nationality: 'South Korea', nationalityCode: 'KR', position: 'LW', dateOfBirth: '1992-07-08', team: 'Tottenham', league: 'Premier League', category: 'HERO' },
  { name: 'Eden Hazard', firstName: 'Eden', lastName: 'Hazard', nationality: 'Belgium', nationalityCode: 'BE', position: 'LW', dateOfBirth: '1991-01-07', team: 'Real Madrid', league: 'La Liga', category: 'HERO' },
  { name: 'Manuel Neuer', firstName: 'Manuel', lastName: 'Neuer', nationality: 'Germany', nationalityCode: 'DE', position: 'GK', dateOfBirth: '1986-03-27', team: 'Bayern Munich', league: 'Bundesliga', category: 'HERO' },
  { name: 'Marc-André ter Stegen', firstName: 'Marc-André', lastName: 'ter Stegen', nationality: 'Germany', nationalityCode: 'DE', position: 'GK', dateOfBirth: '1992-04-30', team: 'Barcelona', league: 'La Liga', category: 'HERO' },
  { name: 'Karim Benzema', firstName: 'Karim', lastName: 'Benzema', nationality: 'France', nationalityCode: 'FR', position: 'ST', dateOfBirth: '1987-12-19', team: 'Al-Ittihad', league: 'Saudi Pro League', category: 'HERO' },
  { name: 'Luis Suárez', firstName: 'Luis', lastName: 'Suárez', nationality: 'Uruguay', nationalityCode: 'UY', position: 'ST', dateOfBirth: '1987-01-24', team: 'Inter Miami', league: 'MLS', category: 'HERO' },
  { name: 'Philippe Coutinho', firstName: 'Philippe', lastName: 'Coutinho', nationality: 'Brazil', nationalityCode: 'BR', position: 'CAM', dateOfBirth: '1992-06-12', team: 'Vasco da Gama', league: 'Campeonato Brasileiro', category: 'HERO' },
  { name: 'Marcelo', firstName: 'Marcelo', lastName: 'Vieira', nationality: 'Brazil', nationalityCode: 'BR', position: 'LB', dateOfBirth: '1988-05-12', team: 'Fluminense', league: 'Campeonato Brasileiro', category: 'HERO' },
  { name: 'Dani Alves', firstName: 'Dani', lastName: 'Alves', nationality: 'Brazil', nationalityCode: 'BR', position: 'RB', dateOfBirth: '1983-05-06', team: 'Bahia', league: 'Campeonato Brasileiro', category: 'HERO' },

  // ===== CURRENT =====
  { name: 'Jude Bellingham', firstName: 'Jude', lastName: 'Bellingham', nationality: 'England', nationalityCode: 'GB', position: 'CM', dateOfBirth: '2003-06-29', team: 'Real Madrid', league: 'La Liga', category: 'CURRENT' },
  { name: 'Vinicius Jr', firstName: 'Vinícius', lastName: 'Júnior', nationality: 'Brazil', nationalityCode: 'BR', position: 'LW', dateOfBirth: '2000-07-12', team: 'Real Madrid', league: 'La Liga', category: 'CURRENT' },
  { name: 'Bukayo Saka', firstName: 'Bukayo', lastName: 'Saka', nationality: 'England', nationalityCode: 'GB', position: 'RW', dateOfBirth: '2001-09-05', team: 'Arsenal', league: 'Premier League', category: 'CURRENT' },
  { name: 'Phil Foden', firstName: 'Phil', lastName: 'Foden', nationality: 'England', nationalityCode: 'GB', position: 'CAM', dateOfBirth: '2000-05-21', team: 'Manchester City', league: 'Premier League', category: 'CURRENT' },
  { name: 'Jamal Musiala', firstName: 'Jamal', lastName: 'Musiala', nationality: 'Germany', nationalityCode: 'DE', position: 'CAM', dateOfBirth: '2003-02-26', team: 'Bayern Munich', league: 'Bundesliga', category: 'CURRENT' },
  { name: 'Florian Wirtz', firstName: 'Florian', lastName: 'Wirtz', nationality: 'Germany', nationalityCode: 'DE', position: 'CAM', dateOfBirth: '2003-05-03', team: 'Bayer Leverkusen', league: 'Bundesliga', category: 'CURRENT' },
  { name: 'Pedri', firstName: 'Pedro', lastName: 'González', nationality: 'Spain', nationalityCode: 'ES', position: 'CM', dateOfBirth: '2002-11-25', team: 'Barcelona', league: 'La Liga', category: 'CURRENT' },
  { name: 'Gavi', firstName: 'Pablo', lastName: 'Páez', nationality: 'Spain', nationalityCode: 'ES', position: 'CM', dateOfBirth: '2004-08-05', team: 'Barcelona', league: 'La Liga', category: 'CURRENT' },
  { name: 'Rodrygo', firstName: 'Rodrygo', lastName: 'Silva', nationality: 'Brazil', nationalityCode: 'BR', position: 'RW', dateOfBirth: '2001-01-09', team: 'Real Madrid', league: 'La Liga', category: 'CURRENT' },
  { name: 'Federico Valverde', firstName: 'Federico', lastName: 'Valverde', nationality: 'Uruguay', nationalityCode: 'UY', position: 'CM', dateOfBirth: '1998-07-22', team: 'Real Madrid', league: 'La Liga', category: 'CURRENT' },
  { name: 'Aurélien Tchouaméni', firstName: 'Aurélien', lastName: 'Tchouaméni', nationality: 'France', nationalityCode: 'FR', position: 'CDM', dateOfBirth: '2000-01-27', team: 'Real Madrid', league: 'La Liga', category: 'CURRENT' },
  { name: 'William Saliba', firstName: 'William', lastName: 'Saliba', nationality: 'France', nationalityCode: 'FR', position: 'CB', dateOfBirth: '2001-03-24', team: 'Arsenal', league: 'Premier League', category: 'CURRENT' },
  { name: 'Rúben Dias', firstName: 'Rúben', lastName: 'Dias', nationality: 'Portugal', nationalityCode: 'PT', position: 'CB', dateOfBirth: '1997-05-14', team: 'Manchester City', league: 'Premier League', category: 'CURRENT' },
  { name: 'Alisson', firstName: 'Alisson', lastName: 'Becker', nationality: 'Brazil', nationalityCode: 'BR', position: 'GK', dateOfBirth: '1992-10-02', team: 'Liverpool', league: 'Premier League', category: 'CURRENT' },
  { name: 'Thibaut Courtois', firstName: 'Thibaut', lastName: 'Courtois', nationality: 'Belgium', nationalityCode: 'BE', position: 'GK', dateOfBirth: '1992-05-11', team: 'Real Madrid', league: 'La Liga', category: 'CURRENT' },
  { name: 'Ousmane Dembélé', firstName: 'Ousmane', lastName: 'Dembélé', nationality: 'France', nationalityCode: 'FR', position: 'RW', dateOfBirth: '1997-05-15', team: 'Paris Saint-Germain', league: 'Ligue 1', category: 'CURRENT' },
  { name: 'Khvicha Kvaratskhelia', firstName: 'Khvicha', lastName: 'Kvaratskhelia', nationality: 'Georgia', nationalityCode: 'GE', position: 'LW', dateOfBirth: '2001-02-19', team: 'Napoli', league: 'Serie A', category: 'CURRENT' },
  { name: 'Victor Osimhen', firstName: 'Victor', lastName: 'Osimhen', nationality: 'Nigeria', nationalityCode: 'NG', position: 'ST', dateOfBirth: '1998-12-29', team: 'Galatasaray', league: 'Süper Lig', category: 'CURRENT' },
  { name: 'Julian Alvarez', firstName: 'Julián', lastName: 'Álvarez', nationality: 'Argentina', nationalityCode: 'AR', position: 'ST', dateOfBirth: '2000-01-31', team: 'Atlético Madrid', league: 'La Liga', category: 'CURRENT' },
  { name: 'Federico Chiesa', firstName: 'Federico', lastName: 'Chiesa', nationality: 'Italy', nationalityCode: 'IT', position: 'RW', dateOfBirth: '1997-10-25', team: 'Liverpool', league: 'Premier League', category: 'CURRENT' },
  { name: 'Martin Ødegaard', firstName: 'Martin', lastName: 'Ødegaard', nationality: 'Norway', nationalityCode: 'NO', position: 'CM', dateOfBirth: '1998-12-17', team: 'Arsenal', league: 'Premier League', category: 'CURRENT' },
  { name: 'Declan Rice', firstName: 'Declan', lastName: 'Rice', nationality: 'England', nationalityCode: 'GB', position: 'CDM', dateOfBirth: '1999-01-14', team: 'Arsenal', league: 'Premier League', category: 'CURRENT' },
  { name: 'Josko Gvardiol', firstName: 'Joško', lastName: 'Gvardiol', nationality: 'Croatia', nationalityCode: 'HR', position: 'CB', dateOfBirth: '2002-01-23', team: 'Manchester City', league: 'Premier League', category: 'CURRENT' },
  { name: 'Theo Hernández', firstName: 'Theo', lastName: 'Hernández', nationality: 'France', nationalityCode: 'FR', position: 'LB', dateOfBirth: '1997-10-06', team: 'AC Milan', league: 'Serie A', category: 'CURRENT' },
  { name: 'Achraf Hakimi', firstName: 'Achraf', lastName: 'Hakimi', nationality: 'Morocco', nationalityCode: 'MA', position: 'RB', dateOfBirth: '1998-11-04', team: 'Paris Saint-Germain', league: 'Ligue 1', category: 'CURRENT' },
  { name: 'Dominik Szoboszlai', firstName: 'Dominik', lastName: 'Szoboszlai', nationality: 'Hungary', nationalityCode: 'HU', position: 'CM', dateOfBirth: '2000-10-25', team: 'Liverpool', league: 'Premier League', category: 'CURRENT' },
  { name: 'Raphinha', firstName: 'Raphael', lastName: 'Dias', nationality: 'Brazil', nationalityCode: 'BR', position: 'RW', dateOfBirth: '1996-12-14', team: 'Barcelona', league: 'La Liga', category: 'CURRENT' },
  { name: 'Lautaro Martínez', firstName: 'Lautaro', lastName: 'Martínez', nationality: 'Argentina', nationalityCode: 'AR', position: 'ST', dateOfBirth: '1997-08-22', team: 'Inter Milan', league: 'Serie A', category: 'CURRENT' },
  { name: 'Marcus Rashford', firstName: 'Marcus', lastName: 'Rashford', nationality: 'England', nationalityCode: 'GB', position: 'LW', dateOfBirth: '1997-10-31', team: 'Manchester United', league: 'Premier League', category: 'CURRENT' },
  { name: 'Bruno Fernandes', firstName: 'Bruno', lastName: 'Fernandes', nationality: 'Portugal', nationalityCode: 'PT', position: 'CM', dateOfBirth: '1994-09-08', team: 'Manchester United', league: 'Premier League', category: 'CURRENT' },
  { name: 'Gabriel Jesus', firstName: 'Gabriel', lastName: 'Jesus', nationality: 'Brazil', nationalityCode: 'BR', position: 'ST', dateOfBirth: '1997-04-03', team: 'Arsenal', league: 'Premier League', category: 'CURRENT' },
  { name: 'Frenkie de Jong', firstName: 'Frenkie', lastName: 'de Jong', nationality: 'Netherlands', nationalityCode: 'NL', position: 'CM', dateOfBirth: '1997-05-12', team: 'Barcelona', league: 'La Liga', category: 'CURRENT' },
  { name: 'Reece James', firstName: 'Reece', lastName: 'James', nationality: 'England', nationalityCode: 'GB', position: 'RB', dateOfBirth: '1999-12-08', team: 'Chelsea', league: 'Premier League', category: 'CURRENT' },
  { name: 'Emi Martínez', firstName: 'Emiliano', lastName: 'Martínez', nationality: 'Argentina', nationalityCode: 'AR', position: 'GK', dateOfBirth: '1992-09-02', team: 'Aston Villa', league: 'Premier League', category: 'CURRENT' },
  { name: 'Ederson', firstName: 'Ederson', lastName: 'Moraes', nationality: 'Brazil', nationalityCode: 'BR', position: 'GK', dateOfBirth: '1993-08-17', team: 'Manchester City', league: 'Premier League', category: 'CURRENT' },
  { name: 'Antonio Rüdiger', firstName: 'Antonio', lastName: 'Rüdiger', nationality: 'Germany', nationalityCode: 'DE', position: 'CB', dateOfBirth: '1993-03-03', team: 'Real Madrid', league: 'La Liga', category: 'CURRENT' },
  { name: 'Fabinho', firstName: 'Fábio', lastName: 'Henriques', nationality: 'Brazil', nationalityCode: 'BR', position: 'CDM', dateOfBirth: '1993-10-23', team: 'Al-Ittihad', league: 'Saudi Pro League', category: 'CURRENT' },
  { name: 'Bernardo Silva', firstName: 'Bernardo', lastName: 'Silva', nationality: 'Portugal', nationalityCode: 'PT', position: 'CM', dateOfBirth: '1994-08-10', team: 'Manchester City', league: 'Premier League', category: 'CURRENT' },
  { name: 'Kai Havertz', firstName: 'Kai', lastName: 'Havertz', nationality: 'Germany', nationalityCode: 'DE', position: 'ST', dateOfBirth: '1999-06-11', team: 'Arsenal', league: 'Premier League', category: 'CURRENT' },
  { name: 'Mitchell Baker', firstName: 'Mitchell', lastName: 'Baker', nationality: 'Netherlands', nationalityCode: 'NL', position: 'CB', dateOfBirth: '2001-06-27', team: 'Liverpool', league: 'Premier League', category: 'CURRENT' },

  // ===== RETIRED =====
  { name: 'David Villa', firstName: 'David', lastName: 'Villa', nationality: 'Spain', nationalityCode: 'ES', position: 'ST', dateOfBirth: '1981-12-03', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Wesley Sneijder', firstName: 'Wesley', lastName: 'Sneijder', nationality: 'Netherlands', nationalityCode: 'NL', position: 'CAM', dateOfBirth: '1984-06-09', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Filippo Inzaghi', firstName: 'Filippo', lastName: 'Inzaghi', nationality: 'Italy', nationalityCode: 'IT', position: 'ST', dateOfBirth: '1973-08-09', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Claude Makélélé', firstName: 'Claude', lastName: 'Makélélé', nationality: 'France', nationalityCode: 'FR', position: 'CDM', dateOfBirth: '1973-02-18', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Pavel Nedved', firstName: 'Pavel', lastName: 'Nedved', nationality: 'Czech Republic', nationalityCode: 'CZ', position: 'LM', dateOfBirth: '1972-08-30', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Michael Owen', firstName: 'Michael', lastName: 'Owen', nationality: 'England', nationalityCode: 'GB', position: 'ST', dateOfBirth: '1979-12-14', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Ruud van Nistelrooy', firstName: 'Ruud', lastName: 'van Nistelrooy', nationality: 'Netherlands', nationalityCode: 'NL', position: 'ST', dateOfBirth: '1976-07-01', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Raúl', firstName: 'Raúl', lastName: 'González', nationality: 'Spain', nationalityCode: 'ES', position: 'ST', dateOfBirth: '1977-06-27', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Ryan Giggs', firstName: 'Ryan', lastName: 'Giggs', nationality: 'Wales', nationalityCode: 'GB', position: 'LM', dateOfBirth: '1973-11-29', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Henrik Larsson', firstName: 'Henrik', lastName: 'Larsson', nationality: 'Sweden', nationalityCode: 'SE', position: 'ST', dateOfBirth: '1971-09-20', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Javier Zanetti', firstName: 'Javier', lastName: 'Zanetti', nationality: 'Argentina', nationalityCode: 'AR', position: 'RB', dateOfBirth: '1973-08-10', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Francesco Totti', firstName: 'Francesco', lastName: 'Totti', nationality: 'Italy', nationalityCode: 'IT', position: 'CAM', dateOfBirth: '1976-09-27', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Oliver Kahn', firstName: 'Oliver', lastName: 'Kahn', nationality: 'Germany', nationalityCode: 'DE', position: 'GK', dateOfBirth: '1969-06-15', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Rio Ferdinand', firstName: 'Rio', lastName: 'Ferdinand', nationality: 'England', nationalityCode: 'GB', position: 'CB', dateOfBirth: '1978-11-07', team: 'Retired', league: 'Retired', category: 'RETIRED' },
  { name: 'Ashley Cole', firstName: 'Ashley', lastName: 'Cole', nationality: 'England', nationalityCode: 'GB', position: 'LB', dateOfBirth: '1980-12-20', team: 'Retired', league: 'Retired', category: 'RETIRED' },
];

export const PLAYERS: Player[] = RAW_PLAYERS.map((raw, index) => ({
  id: `p-${index}`,
  name: raw.name,
  firstName: raw.firstName,
  lastName: raw.lastName,
  nationality: raw.nationality,
  nationalityCode: raw.nationalityCode,
  position: raw.position,
  role: getRoleFromPosition(raw.position),
  dateOfBirth: raw.dateOfBirth,
  photo: generatePlayerPhoto(raw.name, raw.category, raw.position),
  team: raw.team,
  league: raw.league,
  category: raw.category,
  status: 'AVAILABLE',
}));
